spring.application.name=Spring-Boot-Jwt-Auth
server.port=8090

spring.datasource.url=jdbc:postgresql://localhost:5432/demo
spring.datasource.username=YOUR_DB_USERNAME
spring.datasource.password=YOUR_DB_PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO
logging.level.com.abdelrahman=INFO

# JWT Configuration
# 24 hours
jwt.expiration=86400000

